import prisma from './prisma';
import { triggerNotification, getOrCreatePreferences } from './services/notificationService';

async function runTests() {
  console.log('🧪 Starting LunaCare Notification Integration Tests...');

  // 1. Find or create a test user
  let testUser = await prisma.user.findFirst();
  if (!testUser) {
    console.log('Creating mock test user...');
    testUser = await prisma.user.create({
      data: {
        firstName: 'Test',
        lastName: 'User',
        passwordHash: 'mock-hash'
      }
    });
  }
  const userId = testUser.id;
  console.log(`User selected: ${testUser.firstName} ${testUser.lastName} (ID: ${userId})`);

  // 2. Test Preferences Get or Create
  console.log('\n--- Test Case 1: Preferences Get/Create ---');
  const prefs = await getOrCreatePreferences(userId);
  if (!prefs) {
    throw new Error('Preferences could not be fetched or created.');
  }
  console.log('Preferences fetched successfully:', {
    userId: prefs.userId,
    dailyReminder: prefs.dailyReminder,
    timezone: prefs.timezone
  });

  // 3. Test Trigger Notification (In-App)
  console.log('\n--- Test Case 2: Trigger In-App Notification ---');
  const initialCount = await prisma.notification.count({ where: { userId } });
  
  const notification = await triggerNotification(
    userId,
    'Integration Test Alert',
    'This is a test notification generated by the automated test suite.',
    'SYSTEM_NOTIFICATIONS',
    'TEST_ALERT',
    { priority: 'HIGH', icon: 'bug_report' }
  );
  
  if (!notification) {
    throw new Error('Notification creation failed (blocked by preference or database error).');
  }
  
  console.log('Notification created in DB successfully:', {
    id: notification.id,
    title: notification.title,
    message: notification.message,
    category: notification.category
  });

  const postCount = await prisma.notification.count({ where: { userId } });
  if (postCount !== initialCount + 1) {
    throw new Error('Database count did not increment.');
  }
  console.log('✅ Count verified.');

  // 4. Test Mark As Read
  console.log('\n--- Test Case 3: Mark Notification Read ---');
  const updated = await prisma.notification.update({
    where: { id: notification.id },
    data: { isRead: true }
  });
  if (!updated.isRead) {
    throw new Error('Notification isRead field was not updated.');
  }
  console.log('✅ Mark read verified.');

  // 5. Test Preferences Update
  console.log('\n--- Test Case 4: Update Preferences ---');
  const updatedPrefs = await prisma.notificationPreference.update({
    where: { userId },
    data: { dailyReminder: false }
  });
  console.log('Successfully set dailyReminder preference to:', updatedPrefs.dailyReminder);

  // Try triggering notification which should be disabled now
  console.log('Attempting to trigger disabled notification...');
  const blockedNotification = await triggerNotification(
    userId,
    'Should Be Blocked',
    'This message should not be saved.',
    'DAILY_REMINDERS',
    'DAILY_LOG_REMINDER'
  );
  
  if (blockedNotification) {
    throw new Error('Notification was sent even though user disabled daily reminders!');
  }
  console.log('✅ Blocked notification check passed.');

  // Re-enable dailyReminder for consistency
  await prisma.notificationPreference.update({
    where: { userId },
    data: { dailyReminder: true }
  });

  // 6. Test Delete Single Notification
  console.log('\n--- Test Case 5: Delete Notification ---');
  await prisma.notification.delete({
    where: { id: notification.id }
  });
  const deleted = await prisma.notification.findUnique({
    where: { id: notification.id }
  });
  if (deleted) {
    throw new Error('Notification was not deleted.');
  }
  console.log('✅ Delete single verified.');

  // 7. Test Clear All Notifications
  console.log('\n--- Test Case 6: Clear All Notifications ---');
  await triggerNotification(userId, 'Alert 1', 'Message 1', 'SYSTEM_NOTIFICATIONS', 'TEST_1');
  await triggerNotification(userId, 'Alert 2', 'Message 2', 'SYSTEM_NOTIFICATIONS', 'TEST_2');
  
  const beforeClearCount = await prisma.notification.count({ where: { userId } });
  console.log(`Notifications before clear: ${beforeClearCount}`);
  
  await prisma.notification.deleteMany({ where: { userId } });
  const afterClearCount = await prisma.notification.count({ where: { userId } });
  console.log(`Notifications after clear: ${afterClearCount}`);
  if (afterClearCount !== 0) {
    throw new Error('Clear all did not delete all notifications.');
  }
  console.log('✅ Clear all verified.');

  console.log('\n🌟 All notification system integration tests passed successfully!');
}

runTests()
  .catch((err) => {
    console.error('❌ Integration tests failed:', err);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });
